language: node_js
node_js:
  - "10.17.0"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng test tfaster-extended-cdk-selection --watch=false --browsers=ChromeHeadless --codeCoverage=true
  - ng build demo tfaster-extended-cdk-selection --prod
  - ng build demo --prod --base-href https://tfaster.github.io/extended-cdk-selection/
after_success:
  - codecov
deploy:
  provider: pages
  skip_cleanup: true # To avoid cleanup of the artifact generated during script
  github_token: $GITHUB_TOKEN # Provided as an environment variable in travis
  local_dir: dist/demo
  on:
    branch: master
