language: node_js
node_js:
  - "10.17.0"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng test tfaster-extended-cdk-selection --watch false --browsers ChromeHeadless
  - ng build --prod --base-href https://github.com/tFaster/ngrid-row-selection-plugin/
